### ISSUE TITLE
Add debug info about failures in CI system using the kubernetes-namespace-report action

### ISSUE THREAD

**Issue by consideRatio** [iovisor/kubectl-trace#201]
I quickly looked at a recent test failure following the merge of #185. For things erroring in tests done in a k8s cluster, it could be relevant to make use of this github action: https://github.com/jupyterhub/action-k8s-namespace-report

I'm a maintainer of the action and we are using it across the jupyterhub org on github.

This is [how we use it](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/84ebc254a8854ade3c1ed2f6f72243ba5be59329/.github/workflows/test-chart.yaml#L372-L377):

```yaml
      # ref: https://github.com/jupyterhub/action-k8s-namespace-report
      - name: Kubernetes namespace report
        uses: jupyterhub/action-k8s-namespace-report@v1
        if: always()
        with:
          important-workloads: deploy/hub deploy/proxy
```

This is how it looks, where it will help provide logs of relevance when it detects something that has errored, or always emit logs by having a workload declared under "important-workloads".

![image](https://github.com/iovisor/kubectl-trace/assets/3837114/72f031e4-d9d6-4e2d-8b1c-9bcbbb0e0c83)
